$(document).ready(function(){
    $('#btnInstalar').click(function(){
        //$('#instalando').fadeIn(900);
        //$('#instalando').fadeOut(5000);
        //$('#instalo').fadeIn(5002);
    });
    $('#btnInstalo').click(function(){
        //$('.subContenido').fadeOut('fast');
    });
    
    $('#btnSincronizar').click(function(){
        //$('#sincroniza').fadeIn(900);
        //$('#sincroniza').fadeOut(6000);
        //$('#sincronizo').fadeIn(6002);
    });
    $('#btnSincronizo').click(function(){
        //$('.subContenido').fadeOut('fast');
    });
});